### ISSUE TITLE
Remove the hardcoded segment secret from the source code

### ISSUE THREAD

**Issue by roopakparikh** [platform9/pf9ctl#117]
https://github.com/platform9/pf9ctl/blob/dca2f17f8d182035e6d4773991db43aa324d24a3/pkg/pmk/segment.go#L14

This should be injected during the compile time (see how version number is injected as an example) instead of being hardcoded

**Comment by anupbarve** [comment]
Created corresponding jira for tracking. https://platform9.atlassian.net/browse/FT-100
Closing this issue.
