### ISSUE TITLE
Use of '#' in the password doesn't work

### ISSUE THREAD

**Issue by roopakparikh** [platform9/pf9ctl#2]
Trying to create a cluster with 3 nodes, using one node to run the pf9ctl, the password on the 'other' hosts contains a '#' and the pf9ctl fails with the Ansible log complaining about problems logging into the other nodes. I have lost the logs with the above incident, but the reproduction is fairly straightforward and doing some research lets me believe that it is because of Ansible limitations.

**Comment by anupbarve** [comment]
Created corresponding jira https://platform9.atlassian.net/browse/FT-102
Since the new CLI does not use ansible, it shouldn't be an issue. Above ticket tracks the `verification` of use of # in password.
