### ISSUE TITLE
pf9ctl build embeds incorrect variables through ldflags

### ISSUE THREAD

**Issue by roopakparikh** [platform9/pf9ctl#33]
go build -o /Users/rparikh/work/src/github.com/platform9/pf9ctl/bin/pf9ctl -ldflags "-X github.com/platform9/cctl/vendor/k8s.io/kubernetes/pkg/version.buildDate=2020-12-14T00:48:24Z -X github.com/platform9/cctl/vendor/k8s.io/kubernetes/pkg/version.gitCommit=916f98dc117352bd2568ce9f93d38be5762ecf1a -X github.com/platform9/cctl/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=dirty"

^^ This is the current build output, it needs to be fixed. check how it is being set and used here: https://github.com/platform9/airctl/commit/72e7e15cbeda42c0d7420bae70d6e12be823f45a
please follow the same pattern

**Comment by anupbarve** [comment]
Created corresponding jira for tracking. https://platform9.atlassian.net/browse/FT-99
Closing this issue.
