### ISSUE TITLE
Make sure pf9ctl can work with ipv6 addresses

### ISSUE THREAD

**Issue by roopakparikh** [platform9/pf9ctl#38]
We fixed few bugs in the python code base specifically to deal with ipv6 addresses on the localhost. Please make sure we don't repeat the same mistakes: https://github.com/platform9/express-cli/commit/d91acf4a3ce5d57631e789d8c7351fdc31abdfb3

**Comment by anupbarve** [comment]
Created corresponding jira for tracking: https://platform9.atlassian.net/browse/FT-101
Closing this issue.
